#uses the REST CLIENT extension to send requests in vscode kind of cool.

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json
Origin: https://final-project-6uo1.onrender.com

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
GET http://localhost:3000/api/v1/workouts/


###
POST http://localhost:3000/api/v1/friends/
Content-Type: application/json

{
    "userId": 0,
    "friendUserId": 10
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
   
    "email": "test@test.com",
    "password": "test"
}

###
PUT http://localhost:3000/api/v1/users/13
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.com",
    "password": "test"
}